
import React, { useState } from 'react';
import { GoogleGenAI, Type } from "@google/genai";
import { GeminiModel } from '../types';

interface AIDetectorViewProps {
  onClose: () => void;
}

const AIDetectorView: React.FC<AIDetectorViewProps> = ({ onClose }) => {
  const [inputText, setInputText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<{
    score: number;
    label: string;
    explanation: string;
    indicators: string[];
  } | null>(null);

  const handleAnalyze = async () => {
    if (!inputText.trim() || isAnalyzing) return;
    setIsAnalyzing(true);
    setResult(null);

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
    try {
      const response = await ai.models.generateContent({
        model: GeminiModel.PRO,
        contents: `Act as a highly advanced AI content detection system. Analyze the following text and determine the probability that it was generated by an AI model (like GPT, Gemini, etc.).
        
        TEXT TO ANALYZE:
        "${inputText}"
        
        Provide your analysis in JSON format with the following schema:
        {
          "score": number (0-100, where 100 is definitely AI),
          "label": string ("Highly Likely AI", "Likely AI", "Possibly AI", "Unlikely AI", "Human Written"),
          "explanation": string (short overview of why),
          "indicators": string[] (list of 3-4 specific linguistic patterns found)
        }`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              score: { type: Type.NUMBER },
              label: { type: Type.STRING },
              explanation: { type: Type.STRING },
              indicators: { type: Type.ARRAY, items: { type: Type.STRING } }
            },
            required: ["score", "label", "explanation", "indicators"]
          }
        }
      });

      const data = JSON.parse(response.text || '{}');
      setResult(data);
    } catch (err) {
      console.error(err);
      alert('Analysis failed. Please try again later.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-[#131314] overflow-hidden">
      {/* Header */}
      <div className="h-16 flex items-center justify-between px-6 border-b border-[#2e2f31]">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-red-500/20 flex items-center justify-center text-red-400">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
          </div>
          <h2 className="text-xl font-medium text-white">AI Content Detector</h2>
        </div>
        <button onClick={onClose} className="p-2 hover:bg-[#2e2f31] rounded-full text-gray-400">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
        </button>
      </div>

      <div className="flex-1 flex flex-col md:flex-row p-6 gap-6 overflow-hidden">
        {/* Input */}
        <div className="flex-1 flex flex-col gap-4">
          <div className="flex justify-between items-center">
            <h3 className="text-sm font-medium text-gray-400">Input Text</h3>
            <span className="text-[10px] text-gray-500 font-bold uppercase">{inputText.length} characters</span>
          </div>
          <textarea 
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Paste text to analyze (min 50 characters for accuracy)..."
            className="flex-1 bg-[#1e1f20] border border-[#3c4043] rounded-3xl p-6 text-white focus:border-red-500/50 outline-none resize-none custom-scrollbar leading-relaxed"
          />
          <button 
            onClick={handleAnalyze}
            disabled={inputText.length < 20 || isAnalyzing}
            className="w-full py-4 bg-red-500/20 text-red-400 border border-red-500/30 font-bold rounded-2xl hover:bg-red-500 hover:text-white transition-all disabled:bg-gray-700 disabled:text-gray-500 disabled:border-transparent shadow-lg"
          >
            {isAnalyzing ? 'Analyzing Patterns...' : 'Analyze Text'}
          </button>
        </div>

        {/* Results */}
        <div className="flex-1 flex flex-col gap-4">
          <h3 className="text-sm font-medium text-gray-400">Detection Results</h3>
          <div className="flex-1 bg-[#0e0e0f] border border-[#2e2f31] rounded-3xl p-8 flex flex-col items-center justify-center text-center relative overflow-hidden group">
            {isAnalyzing ? (
              <div className="flex flex-col items-center gap-6">
                <div className="relative w-24 h-24">
                  <div className="absolute inset-0 rounded-full border-4 border-red-500/10"></div>
                  <div className="absolute inset-0 rounded-full border-t-4 border-red-500 animate-spin"></div>
                </div>
                <p className="text-gray-400 animate-pulse">Scanning linguistic structures...</p>
              </div>
            ) : result ? (
              <div className="w-full space-y-8 animate-in fade-in zoom-in duration-500">
                <div className="space-y-2">
                  <div className="text-6xl font-bold bg-gradient-to-r from-red-500 to-orange-500 bg-clip-text text-transparent">
                    {result.score}%
                  </div>
                  <p className="text-xl font-medium text-white">{result.label}</p>
                </div>

                <div className="p-4 bg-white/5 rounded-2xl text-sm text-gray-300 leading-relaxed border border-white/5">
                  {result.explanation}
                </div>

                <div className="space-y-3">
                  <h4 className="text-[10px] font-bold text-gray-500 uppercase tracking-widest text-left px-2">Key Indicators</h4>
                  <div className="grid grid-cols-1 gap-2">
                    {result.indicators.map((indicator, i) => (
                      <div key={i} className="flex items-center gap-3 p-3 bg-[#1e1f20] rounded-xl border border-white/5 text-xs text-gray-400 text-left">
                        <div className="w-1.5 h-1.5 rounded-full bg-red-500"></div>
                        {indicator}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center space-y-4 opacity-30">
                <svg className="w-16 h-16 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <p className="text-gray-400 italic">Analysis data will appear here.</p>
              </div>
            )}
          </div>

          <div className="p-4 bg-blue-500/5 rounded-2xl border border-blue-500/10 flex items-center gap-3">
            <svg className="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <p className="text-[10px] text-gray-500 leading-tight">Detection is probabilistic. Accuracy increases with longer, more structured texts. Short or informal snippets may yield false positives.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIDetectorView;
